#!/bin/sh

for file in "/etc/profile" "${HOME}/.profile" "${HOME}/.zprofile" ; do
    if [ -f "${file}" ] ; then
        source "${file}"
    fi
done

export XDG_CURRENT_DESKTOP=sway

dbus-launch --exit-with-session sway
